language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  global:
    secure: "gfu3DCSoUVi/69Dc4cCIHXVYaA6Phgggzs8YL02c6Q/zDQCgiufv2JatRO40cwAu6qqjLXuxoWv+4PbZky0+Mdhn9XLLYq/Fmv4jtWBgTtBxnYxpKqBsLWKT99gDdFbYxm91bf8kg+IaS1S5PXBA3hFkiy0hHrDPPdrNa5CmYgE="

install:
  - pip install numpy pytest python-coveralls pytest-cov
  - pip install -v .
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then pip install sphinx sphinx_rtd_theme==0.1.9; fi

script:
  - py.test --cov pyasdf --cov-report term-missing
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then cd $TRAVIS_BUILD_DIR/doc; make html ; fi

after_success:
  - coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then bash $TRAVIS_BUILD_DIR/.travis-update-gh-pages.sh ; fi
